# File download endpoint — serves generated PDFs and
# metadata.json for a specific job.  Only files that
# were recorded at job completion are accessible, and
# path traversal is explicitly blocked.

from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from backend.app.jobs.manager import job_manager
from backend.app.jobs.models import JobStatus

router = APIRouter()

# MIME types for supported file extensions.
MIME_TYPES = {
    ".pdf": "application/pdf",
    ".json": "application/json",
}


@router.get("/download/{job_id}/{filename}")
async def download_file(job_id: str, filename: str):
    """Download a single file generated by a completed job.

    Security measures:
    - Only files listed in the job's result_files or
      metadata_file are served.
    - Path separators and ".." components are rejected
      to prevent directory traversal.
    - The resolved path must stay inside the job's
      output directory.

    Returns a FileResponse with the appropriate
    Content-Type header.
    """
    # Reject path traversal attempts early.
    if (
        "/" in filename
        or "\\" in filename
        or filename == ".."
        or filename.startswith("..")
    ):
        raise HTTPException(
            status_code=400,
            detail="Invalid filename",
        )

    job = job_manager.get_job(job_id)

    if job is None:
        raise HTTPException(
            status_code=404,
            detail="Job not found",
        )

    if job.status == JobStatus.FAILED:
        raise HTTPException(
            status_code=400,
            detail="Job failed",
        )

    if job.status in (
        JobStatus.QUEUED,
        JobStatus.PROCESSING,
    ):
        raise HTTPException(
            status_code=409,
            detail="Job is still running",
        )

    # Check that the requested file was actually
    # generated by this job.
    allowed = set(job.result_files)
    if job.metadata_file:
        allowed.add(job.metadata_file)

    if filename not in allowed:
        raise HTTPException(
            status_code=404,
            detail="File not found for this job",
        )

    # Build the full path and verify it resolves
    # inside the output directory.
    output_dir = Path(job.output_directory).resolve()
    file_path = (output_dir / filename).resolve()

    if not str(file_path).startswith(str(output_dir)):
        raise HTTPException(
            status_code=400,
            detail="Invalid file path",
        )

    if not file_path.is_file():
        raise HTTPException(
            status_code=404,
            detail="File not found on disk",
        )

    suffix = file_path.suffix.lower()
    media_type = MIME_TYPES.get(
        suffix, "application/octet-stream"
    )

    return FileResponse(
        path=str(file_path),
        media_type=media_type,
        filename=filename,
    )
